name: space_r
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_navigation: ^0.0.4
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.0

flutter:
  uses-material-design: true
